# Generated by Django 4.0.4 on 2022-05-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_data', models.TextField(help_text='Enter the test Data')),
                ('summary', models.TextField(help_text='Enter the test Data')),
            ],
        ),
    ]
