# Generated by Django 4.0.4 on 2022-05-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='book_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='summary',
            field=models.TextField(),
        ),
    ]
