# Generated by Django 4.0.4 on 2022-05-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rename_book_id_data_id_alter_data_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='input_data',
            field=models.TextField(),
        ),
    ]
